public enum EStatInteractionIntent
{
    ADD_STAT_FILTER, REMOVE_STAT_FILTER,
    STAT_GAIN,  ADD_STAT_GAIN_FILTER, REMOVE_STAT_GAIN_FILTER,
    STAT_DEPLETE, ADD_STAT_DEPLETE_FILTER, REMOVE_STAT_DEPLETE_FILTER,
}
